# Jekyll configuration
markdown: kramdown
kramdown:
  parse_block_html: true
# kramdown : markdown에서 불편한 사항을 개선한 형태.
encoding: 'UTF-8'

# MyData
owner:
  name:           Heuristic Wave
  avatar:         photo.jpg
  bio:            "Bachelor's in Computer Science"
  email:          heuristicwave@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

highlighter: rouge
# 2016.02월 이후로 syntax highlighter는 rouge만 지원.
# Pygments 사용불가.

paginate: 20

language: 'en-uk'

url: https://heuristicwave.github.io
# sitemap.xml 생성시, 이 url key값이 존재하지 않으면 sitemap.xml이
# 정상적으로 생성되지 않는다.
# 또한 disqus(댓글시스템)를 이용하기 위해서도 필요.

baseurl: /

# Website info
title: Heuristic Wave Blog

description: Careful Writer

cover: assets/built/images/blog-cover.jpg

logo:
logo_dark:

favicon: assets/built/images/water-wave-48.png

production_url: https://heuristicwave.github.io

source_url: https://github.com/heuristicwave/GitHubPageMaker
# blogmaker(jekyll source folder)에 대한 github repository

# Social info
navigation: True
# Navigation bar link를 보여줄건지 여부

subscribers: True
# subscriber 기능을 사용할건지의 여부
# 저는 약간의 수정을 통해 subscriber 기능대신
# lunr.js를 이용한 검색 기능으로 대체 사용했습니다.
# 검색기능으로 대체하기 위해서
# `_includes/subscribe-form.html` 파일의 수정이 필요합니다.

twitter:
facebook:
# 만약 twitter와 facebook을 이용하면 username을 입력

# Disqus
disqus: True
disqus_shortname: heuristicwave-github-io

# Google Analytics
google_analytics: G-0FTXSPJZFY

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:title
# 각각의 post에 고정주소를 어떤 방식으로 할당할 것인지를 결정
# 이 값을 바꾸면 작성한 포스트의 저장위치나 파일이름이 변경된다.

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]

feed:
  path: feed.xml

# Travis-CI 설정입니다.
safe: False
lsi: False

username: heuristicwave
repo: GitHubPageMaker

branch: master

relative_source:

# compile된 결과가 생성되는 폴더
destination: ./output/

# exclude는 Jekyll컴파일 시 destination에 포함될 필요가 없는 것 명시
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - assets/css
  - assets/images
  - _posts/et-cetera