version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo Installing dependencies...
      - gem install bundler
      - bundle install --quiet
  pre_build:
    commands:
      - export LC_ALL="en_US.utf8"
  build:
    commands:
      - echo Building...
      - bundle exec rake site:deploy