version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo Installing dependencies...
      - gem install bundler
      - bundle install --quiet
  pre_build:
    commands:
      - echo Git Setting...
#      - mkdir -p ~/.ssh
#      - echo "$build_ssh_key" > ~/.ssh/id_rsa
#      - chmod 600 ~/.ssh/id_rsa
#      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
#      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - ls
      - sleep 5
      - mkdir buildZone && cd buildZone
      - git init
      - git remote add origin https://$GITHUB_TOKEN@github.com/heuristicwave/GitHubPageMaker.git
      - git fetch
      - git checkout -t origin/master
  build:
    commands:
      - echo Building...
      - bundle exec rake site:deploy --trace # --quiet
  post_build:
    commands:
      - echo Submodule Updating...
#      - git submodule init
#      - git submodule update --recursive
