version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo Installing dependencies...
      - gem install bundler
      - bundle install --quiet
  pre_build:
    commands:
      - echo Git Setting...
      - git status
      - mkdir buildZone && cd buildZone
      - git init
      - git remote add origin https://$GITHUB_TOKEN@github.com/heuristicwave/GitHubPageMaker.git
      - git fetch
#      - git clean -d -f -f
#      - git checkout -t origin/master
  build:
    commands:
      - echo Building...
      - bundle exec rake site:deploy # --quiet --trace
  post_build:
    commands:
      - echo Finish